### ISSUE TITLE
Model conversion from mixed precision to full precision fails

### ISSUE THREAD

**Issue by dbouget** [andreped/GradientAccumulator#36] opened 2023-02-17 12:02 UTC
Error collected: 
```
File "/home/dbouget/Code/Private/neuro-segmentation/venv/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1864, in set_weights
    raise ValueError(
ValueError: Layer gradient_accumulate_model weight shape (3, 3, 3, 1, 16) is not compatible with provided weight shape ().
```

Code ran:
```
mixed_model = load_model(mixed_precision_model_filepath, compile=False)
full_model = network.create()

full_model = GradientAccumulateModel(
    accum_steps=accumulated_gradients,
    mixed_precision=use_mixed_precision,
    use_agc=adaptive_gradient_clipping,
    clip_factor=0.01, eps=1e-3,
    inputs=full_model.input,
    outputs=full_model.output)

full_model.set_weights(mixed_model.get_weights())
```

Details: I've printed the weights' shapes for the mixed_precision model (top) and full_precision model (bottom). The difference is in bold (tough to see though) where a layer with no shape () and of type int32 is in between the encoder and decoder path for the mixprec model, but at the end for the fullprec model.

```
[(3, 3, 3, 1, 16), (16,), (3, 3, 3, 16, 16), (16,), (3, 3, 3, 1, 32), (32,), (3, 3, 3, 48, 32), (32,), (3, 3, 3, 32, 32), (32,), (3, 3, 3, 1, 128), (128,), (3, 3, 3, 160, 128), (128,), (3, 3, 3, 128, 128), (128,), (3, 3, 3, 1, 256), (256,), (3, 3, 3, 384, 256), (256,), (3, 3, 3, 256, 256), (256,), (3, 3, 3, 256, 256), (256,), (3, 3, 3, 256, 256), (256,), (3, 3, 3, 256, 256), (256,), (1, 1, 1, 256, 128), (128,), (1, 1, 1, 256, 128), (128,), (1, 1, 1, 256, 1), (1,), (3, 3, 3, 512, 256), (256,), (3, 3, 3, 256, 256), (256,), (3, 3, 3, 128, 256), (128,), (1, 1, 1, 128, 64), (64,), (1, 1, 1, 128, 64), (64,), (1, 1, 1, 128, 1), (1,), (3, 3, 3, 256, 128), (128,), (3, 3, 3, 128, 128), (128,), (3, 3, 3, 32, 128), (32,), (1, 1, 1, 32, 16), (16,), (1, 1, 1, 32, 16), (16,), (1, 1, 1, 32, 1), (1,), (3, 3, 3, 64, 32), (32,), (3, 3, 3, 32, 32), (32,), (3, 3, 3, 16, 32), (16,), (1, 1, 1, 16, 8), (8,), (1, 1, 1, 16, 8), (8,), (1, 1, 1, 16, 1), (1,), (3, 3, 3, 32, 16), (16,), (3, 3, 3, 16, 16), (16,), (1, 1, 1, 16, 2), (2,), (1, 1, 1, 32, 2), (2,), (1, 1, 1, 128, 2), (2,), (1, 1, 1, 256, 2), (2,), **(),** (3, 3, 3, 1, 16), (16,), (3, 3, 3, 16, 16), (16,), (3, 3, 3, 1, 32), (32,), (3, 3, 3, 48, 32), (32,), (3, 3, 3, 32, 32), (32,), (3, 3, 3, 1, 128), (128,), (3, 3, 3, 160, 128), (128,), (3, 3, 3, 128, 128), (128,), (3, 3, 3, 1, 256), (256,), (3, 3, 3, 384, 256), (256,), (3, 3, 3, 256, 256), (256,), (3, 3, 3, 256, 256), (256,), (3, 3, 3, 256, 256), (256,), (3, 3, 3, 256, 256), (256,), (1, 1, 1, 256, 128), (128,), (1, 1, 1, 256, 128), (128,), (1, 1, 1, 256, 1), (1,), (3, 3, 3, 512, 256), (256,), (3, 3, 3, 256, 256), (256,), (3, 3, 3, 128, 256), (128,), (1, 1, 1, 128, 64), (64,), (1, 1, 1, 128, 64), (64,), (1, 1, 1, 128, 1), (1,), (3, 3, 3, 256, 128), (128,), (3, 3, 3, 128, 128), (128,), (3, 3, 3, 32, 128), (32,), (1, 1, 1, 32, 16), (16,), (1, 1, 1, 32, 16), (16,), (1, 1, 1, 32, 1), (1,), (3, 3, 3, 64, 32), (32,), (3, 3, 3, 32, 32), (32,), (3, 3, 3, 16, 32), (16,), (1, 1, 1, 16, 8), (8,), (1, 1, 1, 16, 8), (8,), (1, 1, 1, 16, 1), (1,), (3, 3, 3, 32, 16), (16,), (3, 3, 3, 16, 16), (16,), (1, 1, 1, 16, 2), (2,), (1, 1, 1, 32, 2), (2,), (1, 1, 1, 128, 2), (2,), (1, 1, 1, 256, 2), (2,)]

[(3, 3, 3, 1, 16), (16,), (3, 3, 3, 16, 16), (16,), (3, 3, 3, 1, 32), (32,), (3, 3, 3, 48, 32), (32,), (3, 3, 3, 32, 32), (32,), (3, 3, 3, 1, 128), (128,), (3, 3, 3, 160, 128), (128,), (3, 3, 3, 128, 128), (128,), (3, 3, 3, 1, 256), (256,), (3, 3, 3, 384, 256), (256,), (3, 3, 3, 256, 256), (256,), (3, 3, 3, 256, 256), (256,), (3, 3, 3, 256, 256), (256,), (3, 3, 3, 256, 256), (256,), (1, 1, 1, 256, 128), (128,), (1, 1, 1, 256, 128), (128,), (1, 1, 1, 256, 1), (1,), (3, 3, 3, 512, 256), (256,), (3, 3, 3, 256, 256), (256,), (3, 3, 3, 128, 256), (128,), (1, 1, 1, 128, 64), (64,), (1, 1, 1, 128, 64), (64,), (1, 1, 1, 128, 1), (1,), (3, 3, 3, 256, 128), (128,), (3, 3, 3, 128, 128), (128,), (3, 3, 3, 32, 128), (32,), (1, 1, 1, 32, 16), (16,), (1, 1, 1, 32, 16), (16,), (1, 1, 1, 32, 1), (1,), (3, 3, 3, 64, 32), (32,), (3, 3, 3, 32, 32), (32,), (3, 3, 3, 16, 32), (16,), (1, 1, 1, 16, 8), (8,), (1, 1, 1, 16, 8), (8,), (1, 1, 1, 16, 1), (1,), (3, 3, 3, 32, 16), (16,), (3, 3, 3, 16, 16), (16,), (1, 1, 1, 16, 2), (2,), (1, 1, 1, 32, 2), (2,), (1, 1, 1, 128, 2), (2,), (1, 1, 1, 256, 2), (2,), (3, 3, 3, 1, 16), (16,), (3, 3, 3, 16, 16), (16,), (3, 3, 3, 1, 32), (32,), (3, 3, 3, 48, 32), (32,), (3, 3, 3, 32, 32), (32,), (3, 3, 3, 1, 128), (128,), (3, 3, 3, 160, 128), (128,), (3, 3, 3, 128, 128), (128,), (3, 3, 3, 1, 256), (256,), (3, 3, 3, 384, 256), (256,), (3, 3, 3, 256, 256), (256,), (3, 3, 3, 256, 256), (256,), (3, 3, 3, 256, 256), (256,), (3, 3, 3, 256, 256), (256,), (1, 1, 1, 256, 128), (128,), (1, 1, 1, 256, 128), (128,), (1, 1, 1, 256, 1), (1,), (3, 3, 3, 512, 256), (256,), (3, 3, 3, 256, 256), (256,), (3, 3, 3, 128, 256), (128,), (1, 1, 1, 128, 64), (64,), (1, 1, 1, 128, 64), (64,), (1, 1, 1, 128, 1), (1,), (3, 3, 3, 256, 128), (128,), (3, 3, 3, 128, 128), (128,), (3, 3, 3, 32, 128), (32,), (1, 1, 1, 32, 16), (16,), (1, 1, 1, 32, 16), (16,), (1, 1, 1, 32, 1), (1,), (3, 3, 3, 64, 32), (32,), (3, 3, 3, 32, 32), (32,), (3, 3, 3, 16, 32), (16,), (1, 1, 1, 16, 8), (8,), (1, 1, 1, 16, 8), (8,), (1, 1, 1, 16, 1), (1,), (3, 3, 3, 32, 16), (16,), (3, 3, 3, 16, 16), (16,), (1, 1, 1, 16, 2), (2,), (1, 1, 1, 32, 2), (2,), (1, 1, 1, 128, 2), (2,), (1, 1, 1, 256, 2), (2,), **()**]
```

Alternative: of course it remains possible to perform the model conversion simply by doing the following, but it prints a lot of warnings as already pointed out in issue #25 .
```
full_model.load_weights(mixed_precision_model_filepath)
```

**Comment by andreped** [comment] 2024-01-21 21:31
@dbouget I refactored your issue slightly, to be more easily readable. I hope that's OK.

The issue is yet to be solved, but I guess as this **only produces lots of warnings**, it is not that critical to fix.

**Comment by andreped** [comment] 2024-01-21 22:47
I am unable to find a fix for this. I believe one could play around with configs to fix the issue, but I tried and I am unable to remove the issue completely.

As this is just a warning, and does not break the code, I am closing this issue.

Feel free to reopen the issue, @dbouget, if you wish to explore it further or if anyone else wants this warning resolved.

**Closed by andreped** 2024-01-21 22:47 UTC
Labels: bug
