### ISSUE TITLE
Model conversion weights size mismatch

### ISSUE THREAD

**Issue by dbouget** [andreped/GradientAccumulator#25] opened 2022-11-07 09:37 UTC
Purpose: converting a trained model's precision from float16 to float32.

Issue: the set_weights method indicates a size mismatch without recreating the model by wrapping it inside the GAModelWrapper, converts fine when wrapped.

**Comment by andreped** [comment] 2022-11-08 20:13
I was unable to reproduce this issue. See [gist](https://colab.research.google.com/gist/andreped/d072cba4ecd2a28b2a3686bf1768f36a/ga_set_weights_test.ipynb).

You did not by accident use `set_weights()` instead of `load_weights()`?

**Comment by dbouget** [comment] 2022-11-11 09:01
I have tried with `load_weights()` directly on the non-wrapped model, which does not crash and produces a new model. But I am getting plenty of warnings (most likely for all variables linked to the GAModelWrapper).

Some example: 
`WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer's state 'v' for (root).layer_with_weights-40.bias
WARNING:tensorflow:Detecting that an object or model or tf.train.Checkpoint is being deleted with unrestored values. See the following logs for the specific values in question. To silence these warnings, use `status.expect_partial()`. See https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restorefor details about the status object returned by the restore function.
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).accum_step_counter
`

I guess it's fine for running inference, but should be fully wrapped to resume training.

**Comment by andreped** [comment] 2022-11-11 13:00
@dbouget As you found a fix, I will close this issue.

If these warning results in any breaking issues, please, let me know and I will re-open the issue again.

**Closed by andreped** 2022-11-11 13:00 UTC
Labels: bug
